# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\mtuzo\OneDrive\Рабочий стол\Даша\Проект по pyqt5\категории.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow2(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(423, 316)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.text_name_category = QtWidgets.QLineEdit(self.centralwidget)
        self.text_name_category.setGeometry(QtCore.QRect(110, 60, 201, 20))
        self.text_name_category.setObjectName("text_name_category")
        self.label_name = QtWidgets.QLabel(self.centralwidget)
        self.label_name.setGeometry(QtCore.QRect(170, 30, 81, 21))
        self.label_name.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.label_name.setAlignment(QtCore.Qt.AlignCenter)
        self.label_name.setObjectName("label_name")
        self.choice_color = QtWidgets.QPushButton(self.centralwidget)
        self.choice_color.setGeometry(QtCore.QRect(260, 130, 131, 51))
        self.choice_color.setObjectName("choice_color")
        self.random_color = QtWidgets.QPushButton(self.centralwidget)
        self.random_color.setGeometry(QtCore.QRect(30, 130, 131, 51))
        self.random_color.setObjectName("random_color")
        self.label_color = QtWidgets.QLabel(self.centralwidget)
        self.label_color.setGeometry(QtCore.QRect(170, 100, 81, 21))
        self.label_color.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.label_color.setAlignment(QtCore.Qt.AlignCenter)
        self.label_color.setObjectName("label_color")
        self.save_category = QtWidgets.QPushButton(self.centralwidget)
        self.save_category.setGeometry(QtCore.QRect(170, 190, 81, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.save_category.setFont(font)
        self.save_category.setStyleSheet("background-color: rgb(0, 196, 255);")
        self.save_category.setObjectName("save_category")
        self.label_save = QtWidgets.QLabel(self.centralwidget)
        self.label_save.setGeometry(QtCore.QRect(160, 230, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_save.setFont(font)
        self.label_save.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.label_save.setText("")
        self.label_save.setAlignment(QtCore.Qt.AlignCenter)
        self.label_save.setObjectName("label_save")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 423, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_name.setText(_translate("MainWindow", "Название"))
        self.choice_color.setText(_translate("MainWindow", "Выбрать цвет"))
        self.random_color.setText(_translate("MainWindow", "Рандомный цвет"))
        self.label_color.setText(_translate("MainWindow", "Цвет"))
        self.save_category.setText(_translate("MainWindow", "Сохранить"))
